services:
  frontend:
    image: node:22.15-alpine
    working_dir: "/app"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    command: "sh -c 'npm run dev'"

volumes:
  node_modules: